name: CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
    types: [closed]  # Only trigger when PR is merged (not opened/synchronized)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Release Binary
        working-directory: ./src/server
        run: |
          go build -ldflags="-X main.VERSION=${{ steps.version.outputs.VERSION }} -X main.BUILD=${{ github.sha }}" -o hopnpop16 .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hopnpop16-linux
          path: ./src/server/hopnpop16 